### PR TITLE
use request size on conn

### PR DESCRIPTION
**Pull request by xonvanetta**
Use the EDNS OPT size for conn buffer size
created a DNS that's long enough to fill 512 bytes `rip.heib.se`

Signed-off-by: Fabian Heib <11271952+xonvanetta@users.noreply.github.com>

### CODE REVIEW

**Comment by xonvanetta** [comment]
Aww gotta fix those tests

@denis-tingaikin also fixed suggestion from #37
Can remove the upgrade packages but thought it would be a nice to have

**Comment by jonaz** [comment]
@xonvanetta please add the logs with errors so its clear what problem we fix :)

**Comment by denis-tingaikin** [comment]
This is looking valid. Let's resolve the comment https://github.com/networkservicemesh/fanout/pull/42#issuecomment-1037375992 and this can be merged

**Comment by xonvanetta** [comment]
> @xonvanetta please add the logs with errors so its clear what problem we fix :)

`[ERROR] plugin/errors: 2 rip.heib.se. A: attempt limit has been reached, last err: dns: buffer size too small`

**Comment by jonaz** [comment]
ping @denis-tingaikin logs added.

**Comment by denis-tingaikin** [comment]
@xonvanetta Nice!

**Pull request merged**
