### PR TITLE
Add cache plugin to coredns

### PR DESCRIPTION
**Pull request by Bolodya1997**
Adds `cache` plugin to coredns.

### CODE REVIEW

**Comment by edwarnicke** [comment]
I like DNS caching a lot... but am curious what triggered adding this :)

**Comment by Bolodya1997** [comment]
> I like DNS caching a lot... but am curious what triggered adding this :)

Looks like `ping` have some timeout to make DNS resolving - tried locally with setting `10ms` latency between kind nodes and it always fails. And it looks like sometimes it is a problem when we testing it on the real clouds.
So we can start using `nslookup` instead of `ping`, but it probably wouldn't look so good. The other solution we can try is to add `cache` plugin to fix issue with latency between the Client and the Endpoint nodes.

**Comment by denis-tingaikin** [comment]
@edwarnicke Yes, I suggested to use the `cache` to avoid some unexpected issues that @Bolodya1997 found during testing failed build on CI. As side effect it could a bit improve performance for DNS NSM scenarios :)

**Review by denis-tingaikin — APPROVED** [review]

**Comment by denis-tingaikin** [comment]
@edwarnicke Do you have any additional comments on this PR?

**Comment by edwarnicke** [comment]
I am a huge fan of the cache... thank you for explaining what was going on :)

**Pull request merged**
