### PR TITLE
Update coredns dependency to v1.7.1

### PR DESCRIPTION
**Pull request by denis-tingajkin**
Signed-off-by: Denis Tingajkin <denis.tingajkin@xored.com>

## Motivation

https://github.com/networkservicemesh/fanout/issues/26

### CODE REVIEW

**Comment by snakwu** [comment]
Do you need to wait for the new version to be released next time before you can compile on your own?

**Comment by denis-tingajkin** [comment]
@snakwu 
the plugin will be compilable with the latest coredns until they apply changes in plugins API.

**Comment by snakwu** [comment]
> @snakwu 
> the plugin will be compilable with the latest coredns until they apply changes in plugins API.

@denis-tingajkin 
Oh, that's great!
ps：Can you support DOH??

**Comment by snakwu** [comment]
> @snakwu 
> the plugin will be compilable with the latest coredns until they apply changes in plugins API.

Cloning into 'coredns'...
remote: Enumerating objects: 57593, done.                                              remote: Total 57593 (delta 0), reused 0 (delta 0), pack-reused 57593                   Receiving objects: 100% (57593/57593), 95.61 MiB | 14.37 MiB/s, done.
Resolving deltas: 100% (31188/31188), done.
go generate coredns.go
CGO_ENABLED=0  go build -v -ldflags="-s -w -X github.com/coredns/coredns/coremain.GitCommit=aa82ca62-dirty" -o coredns
go: finding github.com/networkservicemesh/fanout latest
github.com/networkservicemesh/fanout
# github.com/networkservicemesh/fanout
../../pkg/mod/github.com/networkservicemesh/fanout@v0.0.0-20200803070946-b663b8bd9437/setup.go:60:3: undefined: metrics.MustRegister
note: module requires Go 1.14
make: *** [Makefile:16: coredns] Error 2

**Pull request merged**
