### PR TITLE
Plugin fanout: update coredns deps

### PR DESCRIPTION
**Pull request by denis-tingajkin**
Signed-off-by: denis-tingajkin <denis.tingajkin@xored.com>

## Motivation

This PR updates dependency on coredns and should fix https://github.com/networkservicemesh/fanout/issues/24

### CODE REVIEW

**Comment by snakwu** [comment]
怎么还没合并？

**Comment by snakwu** [comment]
Cloning into 'coredns'...
remote: Enumerating objects: 25, done.                                                 remote: Counting objects: 100% (25/25), done.                                          remote: Compressing objects: 100% (24/24), done.                                       remote: Total 57045 (delta 5), reused 4 (delta 0), pack-reused 57020                   Receiving objects: 100% (57045/57045), 95.43 MiB | 15.46 MiB/s, done.
Resolving deltas: 100% (30705/30705), done.
go generate coredns.go
CGO_ENABLED=0  go build -v -ldflags="-s -w -X github.com/coredns/coredns/coremain.GitCommit=97530573-dirty" -o coredns
go: finding github.com/networkservicemesh/fanout latest
github.com/networkservicemesh/fanout
# github.com/networkservicemesh/fanout
../../pkg/mod/github.com/networkservicemesh/fanout@v0.0.0-20200803070946-b663b8bd9437/setup.go:60:3: undefined: metrics.MustRegister
note: module requires Go 1.14
make: *** [Makefile:16: coredns] Error 2

**Comment by snakwu** [comment]
@haiodo @denis-tingajkin 
make error！

**Comment by denis-tingajkin** [comment]
@denis-tingajkin Ah, I got it, you are using `make` from the root of coredns project. Will fix in separate PR.

**Comment by denis-tingajkin** [comment]
@snakwu Indeed they have updated the metrics stuff but they did not provide a new version. Currently, the new version is 1.7 that is working fine with fanout plugin. 

Can you just checkout on the tag 1.7?

**Comment by denis-tingajkin** [comment]
@snakwu ```bash
cd $COREDNS_FOLDER
git checkout v1.7.0
make
```

**Comment by snakwu** [comment]
> @snakwu 
> ```bash
> cd $COREDNS_FOLDER
> git checkout v1.7.0
> make
> ```

snakwu@hassio-server:~/go-workspace/src/coredns$ git checkout v1.7.0
git checkout v1.7.0: command not found
snakwu@hassio-server:~/go-workspace/src/coredns$ make                                  CGO_ENABLED=0  go build -v -ldflags="-s -w -X github.com/coredns/coredns/coremain.GitCommit=97530573-dirty" -o coredns
github.com/networkservicemesh/fanout
# github.com/networkservicemesh/fanout
../../pkg/mod/github.com/networkservicemesh/fanout@v0.0.0-20200803070946-b663b8bd9437/setup.go:60:3: undefined: metrics.MustRegister
note: module requires Go 1.14
make: *** [Makefile:16: coredns] Error 2
snakwu@hassio-server:~/go-workspace/src/coredns$

**Comment by denis-tingajkin** [comment]
@snakwu 
Can you try just update tags?
```
git fetch --all --tags
```

**Comment by snakwu** [comment]
> @snakwu 
> Can you try just update tags?
> ```
> git fetch --all --tags
> git checkout v1.7.0
> make
> ```

snakwu@hassio-server:~/go-workspace/src/coredns$ git fetch --all --tags                git fetch --all --tags: command not found
snakwu@hassio-server:~/go-workspace/src/coredns$

**Comment by denis-tingajkin** [comment]
@snakwu Probably you need to upgrade your `git` to be able to fetch tags.

**Comment by snakwu** [comment]
> @snakwu Probably you need to upgrade your `git` to be able to fetch tags.

为什么会这样，以前一直是直接make就可以的了，什么时候修复一下

**Comment by denis-tingajkin** [comment]
@snakwu 
You are trying to set up new corends that officially is not released. The problem will be fixed on fanout plugin side when they have released `v1.8.0`. Please use the latest official version `v1.7.0`.

**Comment by snakwu** [comment]
> @snakwu 
> You are trying to setup new corends that officially is not released. The problem will be fixed on fanout plugin side when they have released `v1.8.0`. Please use the latest official version `v1.7.0`.

snakwu@hassio-server:~/go-workspace/src/coredns$ git branch                            * master
snakwu@hassio-server:~/go-workspace/src/coredns$ git checkout -b v1.70                 Switched to a new branch 'v1.70'
snakwu@hassio-server:~/go-workspace/src/coredns$ git branch             master
* v1.70
snakwu@hassio-server:~/go-workspace/src/coredns$ nano plugin.cfg                       snakwu@hassio-server:~/go-workspace/src/coredns$ make
CGO_ENABLED=0  go build -v -ldflags="-s -w -X github.com/coredns/coredns/coremain.GitCommit=97530573-dirty" -o coredns
github.com/networkservicemesh/fanout
# github.com/networkservicemesh/fanout
../../pkg/mod/github.com/networkservicemesh/fanout@v0.0.0-20200803070946-b663b8bd9437/setup.go:60:3: undefined: metrics.MustRegister
note: module requires Go 1.14
make: *** [Makefile:16: coredns] Error 2
snakwu@hassio-server:~/go-workspace/src/coredns$

**Comment by snakwu** [comment]
> @snakwu 
> You are trying to setup new corends that officially is not released. The problem will be fixed on fanout plugin side when they have released `v1.8.0`. Please use the latest official version `v1.7.0`.

切换了v1.70分支，仍然不行

**Comment by denis-tingajkin** [comment]
@snakwu Can not reproduce

Here is my log on the branch v1.7.0
```
MacBook-Pro-user:coredns user$ make
go generate coredns.go
go: downloading github.com/googleapis/gnostic v0.1.0
CGO_ENABLED=0  go build -v -ldflags="-s -w -X github.com/coredns/coredns/coremain.GitCommit=f59c03d0-dirty" -o coredns
go: finding module for package github.com/networkservicemesh/fanout
go: downloading github.com/networkservicemesh/fanout v0.0.0-20200803070946-b663b8bd9437
go: found github.com/networkservicemesh/fanout in github.com/networkservicemesh/fanout v0.0.0-20200803070946-b663b8bd9437
github.com/coredns/coredns/plugin/pkg/transport
github.com/coredns/coredns/plugin/pkg/uniq
github.com/Azure/go-autorest/autorest/to
go.opencensus.io
go.opencensus.io/trace/internal
github.com/Azure/azure-sdk-for-go/version
go.opencensus.io/internal/tagencoding
k8s.io/apimachinery/pkg/selection
github.com/google/go-cmp/cmp/internal/flags
github.com/google/go-cmp/cmp/internal/diff
k8s.io/utils/integer
k8s.io/utils/buffer
github.com/aws/aws-sdk-go/internal/sdkmath
github.com/aws/aws-sdk-go/aws/client/metadata
github.com/eapache/queue
github.com/openzipkin-contrib/zipkin-go-opentracing/flag
gopkg.in/DataDog/dd-trace-go.v1/internal/version
gopkg.in/DataDog/dd-trace-go.v1/ddtrace/ext
net
github.com/coredns/coredns/plugin/pkg/log
github.com/infobloxopen/go-trees/numtree
github.com/Azure/go-autorest/autorest/date
golang.org/x/crypto/pkcs12/internal/rc2
github.com/coredns/coredns/plugin/cache/freq
github.com/coredns/coredns/plugin/pkg/cache
google.golang.org/api/internal/third_party/uritemplates
os/user
go.opencensus.io/internal
go.opencensus.io/trace/tracestate
go.opencensus.io/resource
go.opencensus.io/tag
github.com/coredns/coredns/plugin/pkg/singleflight
go.opencensus.io/trace
go.opencensus.io/metric/metricdata
go.uber.org/zap/buffer
go.etcd.io/etcd/auth/authpb
go.uber.org/zap/internal/color
go.opencensus.io/metric/metricproducer
go.opencensus.io/stats/internal
go.uber.org/zap/internal/bufferpool
go.opencensus.io/stats
go.uber.org/zap/internal/exit
go.etcd.io/etcd/etcdserver/api/membership/membershippb
go.etcd.io/etcd/mvcc/mvccpb
go.etcd.io/etcd/raft/raftpb
go.opencensus.io/stats/view
go.etcd.io/etcd/etcdserver/api/v3rpc/rpctypes
go.uber.org/zap/zapcore
github.com/coredns/coredns/plugin/pkg/up
k8s.io/apimachinery/third_party/forked/golang/reflect
k8s.io/apimachinery/pkg/fields
k8s.io/apimachinery/pkg/api/resource
k8s.io/apimachinery/pkg/util/sets
k8s.io/klog
go.etcd.io/etcd/raft/tracker
k8s.io/apimachinery/pkg/conversion/queryparams
go.etcd.io/etcd/raft/confchange
k8s.io/apimachinery/pkg/runtime/schema
k8s.io/apimachinery/pkg/conversion
go.etcd.io/etcd/raft
k8s.io/apimachinery/pkg/util/errors
k8s.io/apimachinery/pkg/util/json
k8s.io/apimachinery/pkg/util/validation/field
k8s.io/apimachinery/pkg/util/naming
k8s.io/apimachinery/pkg/types
k8s.io/apimachinery/pkg/util/clock
k8s.io/apimachinery/pkg/util/intstr
k8s.io/apimachinery/pkg/util/cache
github.com/google/go-cmp/cmp/internal/function
github.com/google/go-cmp/cmp/internal/value
sigs.k8s.io/structured-merge-diff/v3/value
k8s.io/apimachinery/pkg/version
golang.org/x/crypto/ssh/terminal
k8s.io/apimachinery/pkg/util/framer
k8s.io/client-go/pkg/version
github.com/google/go-cmp/cmp
sigs.k8s.io/yaml
k8s.io/client-go/tools/metrics
k8s.io/apimachinery/pkg/util/yaml
golang.org/x/time/rate
k8s.io/utils/trace
github.com/googleapis/gnostic/extensions
k8s.io/client-go/util/flowcontrol
k8s.io/client-go/third_party/forked/golang/template
github.com/imdario/mergo
k8s.io/client-go/util/homedir
github.com/aws/aws-sdk-go/aws/awserr
github.com/aws/aws-sdk-go/internal/shareddefaults
github.com/aws/aws-sdk-go/internal/ini
github.com/aws/aws-sdk-go/internal/sync/singleflight
k8s.io/client-go/util/jsonpath
github.com/aws/aws-sdk-go/aws/endpoints
github.com/aws/aws-sdk-go/internal/sdkio
github.com/aws/aws-sdk-go/aws/awsutil
github.com/aws/aws-sdk-go/aws/credentials
github.com/aws/aws-sdk-go/internal/sdkrand
github.com/aws/aws-sdk-go/internal/sdkuri
github.com/aws/aws-sdk-go/internal/strings
github.com/eapache/go-resiliency/breaker
github.com/aws/aws-sdk-go/aws/credentials/processcreds
github.com/golang/snappy
github.com/pierrec/lz4/internal/xxh32
github.com/go-logfmt/logfmt
github.com/pierrec/lz4
github.com/eapache/go-xerial-snappy
github.com/openzipkin-contrib/zipkin-go-opentracing/types
gopkg.in/DataDog/dd-trace-go.v1/ddtrace
gopkg.in/DataDog/dd-trace-go.v1/internal/globalconfig
github.com/openzipkin-contrib/zipkin-go-opentracing/wire
gopkg.in/DataDog/dd-trace-go.v1/ddtrace/internal
gopkg.in/DataDog/dd-trace-go.v1/internal/log
k8s.io/apimachinery/pkg/util/diff
google.golang.org/grpc/credentials/internal
google.golang.org/grpc/internal/syscall
vendor/golang.org/x/net/http/httpproxy
net/textproto
github.com/google/uuid
google.golang.org/grpc/internal/binarylog
crypto/x509
google.golang.org/grpc/stats
google.golang.org/grpc/naming
vendor/golang.org/x/net/http/httpguts
golang.org/x/net/http/httpguts
github.com/coredns/coredns/plugin/pkg/reuseport
golang.org/x/net/internal/socket
github.com/infobloxopen/go-trees/iptree
github.com/prometheus/procfs
github.com/coreos/go-systemd/v22/journal
go.etcd.io/etcd/pkg/systemd
go.etcd.io/etcd/pkg/types
github.com/farsightsec/golang-framestream
k8s.io/apimachinery/pkg/util/validation
k8s.io/client-go/util/connrotation
github.com/spf13/pflag
log/syslog
github.com/DataDog/datadog-go/statsd
golang.org/x/net/ipv4
golang.org/x/net/ipv6
k8s.io/apimachinery/pkg/labels
github.com/rcrowley/go-metrics
k8s.io/client-go/util/keyutil
golang.org/x/crypto/pkcs12
github.com/dgrijalva/jwt-go
crypto/tls
google.golang.org/api/transport/cert
net/http/httptrace
google.golang.org/grpc/credentials
k8s.io/client-go/util/cert
github.com/miekg/dns
github.com/Shopify/sarama
net/http
google.golang.org/grpc/resolver
google.golang.org/grpc/internal/channelz
google.golang.org/grpc/peer
go.etcd.io/etcd/clientv3/credentials
google.golang.org/grpc/balancer
google.golang.org/grpc/internal/resolver/dns
google.golang.org/grpc/resolver/passthrough
go.etcd.io/etcd/clientv3/balancer/resolver/endpoint
google.golang.org/grpc/resolver/dns
github.com/coredns/coredns/plugin/pkg/edns
github.com/coredns/coredns/plugin/pkg/nonwriter
github.com/coredns/coredns/plugin/pkg/rcode
github.com/coredns/coredns/plugin/pkg/response
github.com/coredns/coredns/plugin/file/rrutil
github.com/coredns/coredns/plugin/pkg/dnstest
github.com/coredns/coredns/request
github.com/dnstap/golang-dnstap
github.com/coredns/coredns/plugin/pkg/dnsutil
github.com/coredns/coredns/plugin/file/tree
github.com/coredns/coredns/plugin/etcd/msg
github.com/coredns/coredns/plugin/dnstap/msg
github.com/coredns/coredns/plugin/dnstap/dnstapio
github.com/coredns/coredns/plugin/dnstap/taprw
golang.org/x/net/trace
net/http/httputil
github.com/coredns/coredns/plugin/pkg/doh
golang.org/x/net/http2
github.com/caddyserver/caddy
github.com/Azure/go-autorest/tracing
github.com/prometheus/client_golang/prometheus/promhttp
net/http/cookiejar
github.com/Azure/go-autorest/logger
github.com/Azure/go-autorest/autorest/adal
google.golang.org/api/googleapi
golang.org/x/net/context/ctxhttp
cloud.google.com/go/compute/metadata
go.opencensus.io/trace/propagation
golang.org/x/oauth2/internal
go.opencensus.io/plugin/ochttp/propagation/b3
google.golang.org/api/googleapi/transport
go.opencensus.io/plugin/ochttp
golang.org/x/oauth2
google.golang.org/api/transport/http/internal/propagation
github.com/coredns/coredns/plugin/pkg/parse
github.com/coredns/coredns/plugin/test
github.com/coredns/coredns/plugin/pkg/tls
golang.org/x/oauth2/jwt
github.com/coredns/coredns/plugin
go.uber.org/zap
github.com/Azure/go-autorest/autorest/azure/cli
github.com/Azure/go-autorest/autorest
golang.org/x/oauth2/google
k8s.io/apimachinery/pkg/util/runtime
github.com/coredns/coredns/plugin/metrics/vars
github.com/coredns/coredns/plugin/pkg/trace
github.com/coredns/coredns/plugin/pkg/fall
k8s.io/apimachinery/pkg/runtime
k8s.io/apimachinery/pkg/util/wait
k8s.io/client-go/util/workqueue
github.com/googleapis/gnostic/compiler
github.com/gophercloud/gophercloud
github.com/googleapis/gnostic/OpenAPIv2
github.com/coredns/coredns/plugin/pprof
github.com/aws/aws-sdk-go/aws
github.com/aws/aws-sdk-go/aws/request
github.com/Azure/go-autorest/autorest/azure
github.com/apache/thrift/lib/go/thrift
go.etcd.io/etcd/clientv3/balancer/connectivity
go.etcd.io/etcd/clientv3/balancer/picker
go.etcd.io/etcd/pkg/logutil
go.etcd.io/etcd/clientv3/balancer
github.com/gophercloud/gophercloud/pagination
github.com/gophercloud/gophercloud/openstack/identity/v3/tokens
github.com/Azure/azure-sdk-for-go/services/dns/mgmt/2018-05-01/dns
github.com/Azure/azure-sdk-for-go/services/privatedns/mgmt/2018-09-01/privatedns
github.com/Azure/go-autorest/autorest/azure/auth
github.com/gophercloud/gophercloud/openstack/identity/v2/tenants
github.com/gophercloud/gophercloud/openstack/identity/v2/tokens
github.com/gophercloud/gophercloud/openstack/utils
github.com/aws/aws-sdk-go/aws/client
github.com/gophercloud/gophercloud/openstack
github.com/aws/aws-sdk-go/aws/corehandlers
github.com/aws/aws-sdk-go/private/protocol
github.com/aws/aws-sdk-go/aws/ec2metadata
github.com/aws/aws-sdk-go/private/protocol/rest
github.com/aws/aws-sdk-go/aws/credentials/ec2rolecreds
github.com/aws/aws-sdk-go/private/protocol/query/queryutil
k8s.io/apimachinery/pkg/runtime/serializer/streaming
k8s.io/apimachinery/pkg/runtime/serializer/recognizer
k8s.io/client-go/tools/clientcmd/api
github.com/aws/aws-sdk-go/aws/signer/v4
k8s.io/apimachinery/pkg/runtime/serializer/json
k8s.io/client-go/tools/clientcmd/api/v1
github.com/Azure/azure-sdk-for-go/profiles/latest/dns/mgmt/dns
github.com/aws/aws-sdk-go/private/protocol/xml/xmlutil
github.com/aws/aws-sdk-go/aws/csm
github.com/aws/aws-sdk-go/private/protocol/json/jsonutil
github.com/opentracing-contrib/go-observer
github.com/aws/aws-sdk-go/private/protocol/query
gopkg.in/DataDog/dd-trace-go.v1/ddtrace/tracer
github.com/aws/aws-sdk-go/private/protocol/restxml
github.com/aws/aws-sdk-go/service/sts
github.com/aws/aws-sdk-go/aws/credentials/endpointcreds
github.com/aws/aws-sdk-go/service/route53
github.com/aws/aws-sdk-go/aws/defaults
google.golang.org/grpc/internal/transport
k8s.io/apimachinery/pkg/util/net
github.com/Azure/azure-sdk-for-go/profiles/latest/privatedns/mgmt/privatedns
github.com/aws/aws-sdk-go/service/sts/stsiface
k8s.io/apimachinery/pkg/watch
k8s.io/client-go/transport
github.com/aws/aws-sdk-go/aws/credentials/stscreds
github.com/aws/aws-sdk-go/aws/session
k8s.io/apimachinery/pkg/apis/meta/v1
gopkg.in/DataDog/dd-trace-go.v1/ddtrace/opentracer
github.com/openzipkin-contrib/zipkin-go-opentracing/thrift/gen-go/scribe
github.com/openzipkin-contrib/zipkin-go-opentracing/thrift/gen-go/zipkincore
github.com/openzipkin-contrib/zipkin-go-opentracing
google.golang.org/grpc
github.com/aws/aws-sdk-go/service/route53/route53iface
github.com/coredns/coredns/pb
google.golang.org/api/internal
github.com/googleapis/gax-go/v2
go.etcd.io/etcd/etcdserver/etcdserverpb
google.golang.org/api/internal/gensupport
github.com/coredns/coredns/core/dnsserver
google.golang.org/api/option
google.golang.org/api/option/internaloption
google.golang.org/api/transport/http
k8s.io/apimachinery/pkg/api/errors
k8s.io/apimachinery/pkg/runtime/serializer/protobuf
k8s.io/apimachinery/pkg/api/meta
k8s.io/apimachinery/pkg/apis/meta/v1/unstructured
github.com/coredns/coredns/coremain
github.com/coredns/coredns/plugin/metrics
github.com/coredns/coredns/plugin/any
github.com/coredns/coredns/plugin/pkg/upstream
github.com/coredns/coredns/plugin/bind
github.com/coredns/coredns/plugin/bufsize
github.com/coredns/coredns/plugin/file
github.com/coredns/coredns/plugin/cancel
github.com/coredns/coredns/plugin/chaos
google.golang.org/api/dns/v1
k8s.io/api/core/v1
github.com/coredns/coredns/plugin/acl
github.com/coredns/coredns/plugin/autopath
github.com/coredns/coredns/plugin/cache
github.com/coredns/coredns/plugin/debug
github.com/coredns/coredns/plugin/dns64
github.com/coredns/coredns/plugin/dnssec
github.com/coredns/coredns/plugin/dnstap
github.com/coredns/coredns/plugin/erratic
github.com/coredns/coredns/plugin/errors
github.com/coredns/coredns/plugin/forward
github.com/coredns/coredns/plugin/auto
github.com/coredns/coredns/plugin/grpc
github.com/coredns/coredns/plugin/azure
github.com/coredns/coredns/plugin/health
github.com/coredns/coredns/plugin/hosts
github.com/coredns/coredns/plugin/k8s_external
k8s.io/apimachinery/pkg/runtime/serializer/versioning
k8s.io/client-go/pkg/apis/clientauthentication
k8s.io/client-go/rest/watch
k8s.io/apimachinery/pkg/runtime/serializer
k8s.io/apimachinery/pkg/apis/meta/v1beta1
github.com/coredns/coredns/plugin/metadata
k8s.io/client-go/pkg/apis/clientauthentication/v1alpha1
k8s.io/api/admissionregistration/v1
github.com/coredns/coredns/plugin/clouddns
k8s.io/client-go/pkg/apis/clientauthentication/v1beta1
k8s.io/apimachinery/pkg/apis/meta/internalversion
k8s.io/api/admissionregistration/v1beta1
k8s.io/api/auditregistration/v1alpha1
k8s.io/client-go/plugin/pkg/client/auth/exec
k8s.io/api/authentication/v1
k8s.io/client-go/tools/pager
k8s.io/api/authentication/v1beta1
k8s.io/client-go/rest
k8s.io/api/authorization/v1
k8s.io/api/authorization/v1beta1
k8s.io/api/certificates/v1beta1
k8s.io/client-go/tools/cache
k8s.io/api/coordination/v1
k8s.io/api/coordination/v1beta1
k8s.io/api/flowcontrol/v1alpha1
k8s.io/api/rbac/v1
k8s.io/api/rbac/v1alpha1
k8s.io/api/rbac/v1beta1
k8s.io/client-go/plugin/pkg/client/auth/gcp
k8s.io/client-go/plugin/pkg/client/auth/oidc
k8s.io/client-go/plugin/pkg/client/auth/openstack
k8s.io/client-go/tools/auth
k8s.io/client-go/tools/clientcmd/api/latest
github.com/coredns/coredns/plugin/loadbalance
k8s.io/client-go/tools/clientcmd
github.com/coredns/coredns/plugin/pkg/replacer
github.com/coredns/coredns/plugin/loop
github.com/coredns/coredns/plugin/log
github.com/coredns/coredns/plugin/nsid
github.com/coredns/coredns/plugin/ready
github.com/coredns/coredns/plugin/reload
github.com/coredns/coredns/plugin/rewrite
github.com/coredns/coredns/plugin/root
github.com/coredns/coredns/plugin/route53
github.com/coredns/coredns/plugin/secondary
github.com/coredns/coredns/plugin/sign
github.com/coredns/coredns/plugin/template
github.com/coredns/coredns/plugin/tls
github.com/coredns/coredns/plugin/trace
github.com/coredns/coredns/plugin/transfer
github.com/coredns/coredns/plugin/whoami
github.com/networkservicemesh/fanout
go.etcd.io/etcd/clientv3
github.com/coredns/coredns/plugin/etcd
github.com/coredns/coredns/plugin/kubernetes/object
k8s.io/api/batch/v1
k8s.io/api/apps/v1beta1
k8s.io/api/autoscaling/v2beta2
k8s.io/api/apps/v1
k8s.io/api/autoscaling/v2beta1
k8s.io/api/autoscaling/v1
k8s.io/api/apps/v1beta2
k8s.io/api/discovery/v1alpha1
k8s.io/api/discovery/v1beta1
k8s.io/api/batch/v1beta1
k8s.io/api/batch/v2alpha1
k8s.io/api/events/v1beta1
k8s.io/api/networking/v1
k8s.io/api/networking/v1beta1
k8s.io/api/node/v1alpha1
k8s.io/api/node/v1beta1
k8s.io/api/policy/v1beta1
k8s.io/api/scheduling/v1
k8s.io/api/scheduling/v1alpha1
k8s.io/api/scheduling/v1beta1
k8s.io/api/settings/v1alpha1
k8s.io/api/extensions/v1beta1
k8s.io/api/storage/v1
k8s.io/api/storage/v1alpha1
k8s.io/api/storage/v1beta1
k8s.io/client-go/tools/reference
k8s.io/client-go/kubernetes/scheme
k8s.io/client-go/kubernetes/typed/authentication/v1
k8s.io/client-go/kubernetes/typed/auditregistration/v1alpha1
k8s.io/client-go/kubernetes/typed/admissionregistration/v1beta1
k8s.io/client-go/kubernetes/typed/admissionregistration/v1
k8s.io/client-go/kubernetes/typed/apps/v1beta1
k8s.io/client-go/discovery
k8s.io/client-go/kubernetes/typed/apps/v1
k8s.io/client-go/kubernetes/typed/apps/v1beta2
k8s.io/client-go/kubernetes/typed/authentication/v1beta1
k8s.io/client-go/kubernetes/typed/authorization/v1
k8s.io/client-go/kubernetes/typed/authorization/v1beta1
k8s.io/client-go/kubernetes/typed/autoscaling/v1
k8s.io/client-go/kubernetes/typed/autoscaling/v2beta1
k8s.io/client-go/kubernetes/typed/autoscaling/v2beta2
k8s.io/client-go/kubernetes/typed/batch/v1
k8s.io/client-go/kubernetes/typed/batch/v1beta1
k8s.io/client-go/kubernetes/typed/batch/v2alpha1
k8s.io/client-go/kubernetes/typed/certificates/v1beta1
k8s.io/client-go/kubernetes/typed/coordination/v1
k8s.io/client-go/kubernetes/typed/coordination/v1beta1
k8s.io/client-go/kubernetes/typed/discovery/v1alpha1
k8s.io/client-go/kubernetes/typed/core/v1
k8s.io/client-go/kubernetes/typed/discovery/v1beta1
k8s.io/client-go/kubernetes/typed/events/v1beta1
k8s.io/client-go/kubernetes/typed/extensions/v1beta1
k8s.io/client-go/kubernetes/typed/flowcontrol/v1alpha1
k8s.io/client-go/kubernetes/typed/networking/v1
k8s.io/client-go/kubernetes/typed/networking/v1beta1
k8s.io/client-go/kubernetes/typed/node/v1alpha1
k8s.io/client-go/kubernetes/typed/node/v1beta1
k8s.io/client-go/kubernetes/typed/policy/v1beta1
k8s.io/client-go/kubernetes/typed/rbac/v1
k8s.io/client-go/kubernetes/typed/rbac/v1alpha1
k8s.io/client-go/kubernetes/typed/rbac/v1beta1
k8s.io/client-go/kubernetes/typed/scheduling/v1
k8s.io/client-go/kubernetes/typed/scheduling/v1alpha1
k8s.io/client-go/kubernetes/typed/scheduling/v1beta1
k8s.io/client-go/kubernetes/typed/settings/v1alpha1
k8s.io/client-go/kubernetes/typed/storage/v1
k8s.io/client-go/kubernetes/typed/storage/v1alpha1
k8s.io/client-go/kubernetes/typed/storage/v1beta1
k8s.io/client-go/kubernetes
github.com/coredns/coredns/plugin/kubernetes
github.com/coredns/coredns/core/plugin
github.com/coredns/coredns

```

**Comment by denis-tingajkin** [comment]
@snakwu can you attach your
```
go version
git log //from the root of coredns folder
```

**Comment by snakwu** [comment]
> @snakwu can you attach your
> ```
> go version
> git log //from the root of coredns folder
> ```

go version go1.13.4 linux/amd64

**Comment by denis-tingajkin** [comment]
What is the latest commit hash you see in `git log`?

**Comment by snakwu** [comment]
> What is the latest commit hash you see in `git log`?

no

**Comment by denis-tingajkin** [comment]
@snakwu As I can see your last commit is not the last commit of v1.7.0
Your last hash should be `commit f59c03d09c3a3a12f571ad1087b979325f3dae30 (HEAD, tag: v1.7.0)`

```
commit f59c03d09c3a3a12f571ad1087b979325f3dae30 (HEAD, tag: v1.7.0)
Author: Yong Tang <yong.tang.github@outlook.com>
Date:   Tue Jun 16 08:16:00 2020 -0700

    Update release note date for 1.7.0 (#3950)
    
    Signed-off-by: Yong Tang <yong.tang.github@outlook.com>

commit 8ee4c1fa2f2d4352fac02ce7a38c0a1556365433
Author: Yong Tang <yong.tang.github@outlook.com>
Date:   Mon Jun 15 07:23:25 2020 -0700

    Bump version to 1.7.0 (#3782)
    
    Signed-off-by: Yong Tang <yong.tang.github@outlook.com>
```

**Comment by snakwu** [comment]
> @snakwu As I can see your last commit is not the last commit of v1.7.0
> Your last hash should be `commit f59c03d09c3a3a12f571ad1087b979325f3dae30 (HEAD, tag: v1.7.0)`
> 
> ```
> commit f59c03d09c3a3a12f571ad1087b979325f3dae30 (HEAD, tag: v1.7.0)
> Author: Yong Tang <yong.tang.github@outlook.com>
> Date:   Tue Jun 16 08:16:00 2020 -0700
> 
>     Update release note date for 1.7.0 (#3950)
>     
>     Signed-off-by: Yong Tang <yong.tang.github@outlook.com>
> 
> commit 8ee4c1fa2f2d4352fac02ce7a38c0a1556365433
> Author: Yong Tang <yong.tang.github@outlook.com>
> Date:   Mon Jun 15 07:23:25 2020 -0700
> 
>     Bump version to 1.7.0 (#3782)
>     
>     Signed-off-by: Yong Tang <yong.tang.github@outlook.com>
> ```

为什么会这样呢，我以前的做法是直接git clone coerdns master 然后修改plugin.cfg，再make就ok了，现在变得这么复杂了？

**Comment by snakwu** [comment]
> @snakwu As I can see your last commit is not the last commit of v1.7.0
> Your last hash should be `commit f59c03d09c3a3a12f571ad1087b979325f3dae30 (HEAD, tag: v1.7.0)`
> 
> ```
> commit f59c03d09c3a3a12f571ad1087b979325f3dae30 (HEAD, tag: v1.7.0)
> Author: Yong Tang <yong.tang.github@outlook.com>
> Date:   Tue Jun 16 08:16:00 2020 -0700
> 
>     Update release note date for 1.7.0 (#3950)
>     
>     Signed-off-by: Yong Tang <yong.tang.github@outlook.com>
> 
> commit 8ee4c1fa2f2d4352fac02ce7a38c0a1556365433
> Author: Yong Tang <yong.tang.github@outlook.com>
> Date:   Mon Jun 15 07:23:25 2020 -0700
> 
>     Bump version to 1.7.0 (#3782)
>     
>     Signed-off-by: Yong Tang <yong.tang.github@outlook.com>
> ```

希望能修复下这个问题

**Comment by denis-tingajkin** [comment]
@snakwu 
> 为什么会这样呢，我以前的做法是直接git clone coerdns master 然后修改plugin.cfg，再make就ok了，现在变得这么复杂了？
It is not a safe approach. 
For example, coredns master currently has _testing changes_ which are not released, and some external plugins may is not compilable because they depend on the concrete version to avoid new bugs from the latest not released changes. 

So we'll update coredns version and apply fixes when coredns has released new version :) 

You can simply change your approach to `clone coredns v1.7.0`, `make`

**Comment by snakwu** [comment]
> @snakwu 
> > 为什么会这样呢，我以前的做法是直接git clone coerdns master 然后修改plugin.cfg，再make就ok了，现在变得这么复杂了？
> 
> It is not a safe approach. 
> For example, coredns master currently has _testing changes_ which are not released, and some external plugins may is not compilable because they depend on the concrete version to avoid new bugs from the latest not released changes. 
> 
> So we'll update coredns version and apply fixes when coredns has released new version :) 
> 
> You can simply change your approach to `clone coredns v1.7.0`, `make`

我应该怎么样来git clone v1.7.0

**Comment by denis-tingajkin** [comment]
@snakwu 
There a lot of ways and one of them is just 
```
git clone ...
git checkout v1.7.0
```

**Comment by snakwu** [comment]
> @snakwu 
> There a lot of ways and one of them is just 
> ```
> git clone ...
> git fetch --tags
> git checkout v1.7.0
> ```

snakwu@hassio-server:~/go-workspace/src/coredns$ git fetch --tags                      git fetch --tags: command not found
snakwu@hassio-server:~/go-workspace/src/coredns$ git --version                         git version 2.25.1
snakwu@hassio-server:~/go-workspace/src/coredns$

**Comment by denis-tingajkin** [comment]
@snakwu I think you need to figure out how you can fetch tags from the repository.

**Comment by snakwu** [comment]
不行，仍然无法编译

**Comment by snakwu** [comment]
> @snakwu I think you need to figure out how you can fetch tags from the repository.

ok，已经成功切换v1.7.0，然后成功构建了！但我还是很希望像以前那样，直接可以在master下构建

**Comment by denis-tingajkin** [comment]
@snakwu 
Nice! We'll update this plugin when coredns guys released a new version of coredns :)

**Comment by snakwu** [comment]
> @snakwu 
> Nice! We'll update this plugin when coredns guys released a new version of coredns :)

ok，thx

**Comment by snakwu** [comment]
> @snakwu 
> Nice! We'll update this plugin when coredns guys released a new version of coredns :)

可否让fanout支持doh？？谢谢

**Comment by snakwu** [comment]
@denis-tingajkin  coerdns v1.7.1 is out！

**Pull request merged**
